---
- name: install required packages
  apt:
    name: [ 'wget', 'gnupg2', 'lsb-release', 'curl' ]
    state: present
    update_cache: yes
    
- name: download the percona xtradb repository deb package
  get_url:
    url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    file: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    mode: 644
    
- name: install the downloaded deb file
  shell:
    args: dpkg -i percona-release_latest.generic_all.deb
    
- name: update apt repository
  apt:
    update_cache: yes
    
- name: enable xtradb 8.0 server
  shell:
    args: percona-release setup pxc80
    
- name: install percona xtradb cluster
  apt:
    name: percona-xtradb-cluster-full
    state: present
    update_cache: yes
    
