---
- name: install required packages
  apt:
    name: [ 'wget', 'gnupg2', 'lsb-release', 'curl' ]
    state: present
    update_cache: yes
    
- name: download the percona xtradb repository deb package
  get_url:
    url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    dest: /root/percona-release_latest.generic_all.deb
    mode: 644
    
- name: install the downloaded deb file
  apt:
    deb: /root/percona-release_latest.generic_all.deb
    state: present
    
- name: update apt repository
  apt:
    update_cache: yes
    
- name: enable xtradb 8.0 server
  shell: percona-release setup pxc80
  args:
    executable: /bin/bash
    
- name: install percona xtradb cluster
  apt:
    name: percona-xtradb-cluster-full
    state: present
    update_cache: yes
    
- name: generate id for server
  set_fact:
    id : "{{ ansible_nodename[-1] }}"
    
- debug:
    var: id

- name: generate configuration file from template
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Stop mysql servers
  systemd:
    name: mysql
    state: stopped
    
- name: bootstrap mysql on the first node
  systemd:
    name: mysql@bootstrap
    state: started
  when: inventory_hostname == groups['all'][0]
  
- name: start the rest of the servers 
  systemd:
    name: mysql
    state: started
  when: inventory_hostname != groups['all'][0]
